# Generated by Django 4.2 on 2024-05-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (name of a person)')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
