# Generated by Django 4.2 on 2024-05-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100, verbose_name='Day (name)')),
                ('enterprise', models.CharField(choices=[('Grupo LATAM', 'Grupo LATAM'), ('Sky Airline', 'Sky Airline'), ('Aerolineas Argentinas', 'Aerolineas Argentinas'), ('Copa Air', 'Copa Air'), ('Latin American Wings', 'Latin American Wings'), ('Avianca', 'Avianca'), ('JetSmart SPA', 'JetSmart SPA'), ('Gol Trans', 'Gol Trans'), ('American Airlines', 'American Airlines'), ('Air Canada', 'Air Canada'), ('Iberia', 'Iberia'), ('Delta Air', 'Delta Air'), ('Air France', 'Air France'), ('Aeromexico', 'Aeromexico'), ('United Airlines', 'United Airlines'), ('Oceanair Linhas Aereas', 'Oceanair Linhas Aereas'), ('Alitalia', 'Alitalia'), ('K.L.M.', 'K.L.M.'), ('British Airways', 'British Airways'), ('Qantas Airways', 'Qantas Airways'), ('Lacsa', 'Lacsa'), ('Austral', 'Austral'), ('Plus Ultra Lineas Aereas', 'Plus Ultra Lineas Aereas')], max_length=100, verbose_name='Enterprise')),
                ('month_name', models.CharField(max_length=100, verbose_name='Month (name)')),
                ('date_to_search', models.DateField(verbose_name='Date')),
                ('type_flight', models.CharField(choices=[('I', 'International'), ('N', 'National')], max_length=100, verbose_name='Type (flight)')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
